spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    sql-show: true
    hibernate:
      ddl-auto: create # 주의!
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      name: ${job.name:None}
      enabled: true
    jdbc:
      initialize-schema: ALWAYS

logging.level:
  org.hibernate.SQL: debug
